version: "3.4"
services:
    app:
        container_name: quickstart-lib-app
        build:
            context: .
            dockerfile: .docker/Dockerfile-dev
        volumes:
            - ./../../../../pkg:/go/pkg
            - ./:/go/src/github.com/hoangnguyen1247/quickstart-lib-go
        ports:
            - 4088:4018 # http server
            - 3018:3018 # gprc
            - 2345:2345 # debug
