FROM golang:1.12-alpine

ENV GO111MODULE on
ENV APP_ENV development

RUN apk add bash ca-certificates curl git gcc g++ libc-dev autoconf automake libtool make
RUN mkdir -p /go/src/github.com/hoangnguyen1247/quickstart-lib-go

WORKDIR /go/src/github.com/hoangnguyen1247/quickstart-lib-go

ADD . .

RUN git config --global url."https://9bc010b1ddeb3dba248b721468f91ab85d1886af:x-oauth-basic@github.com/".insteadOf "https://github.com/"

# RUN go get github.com/githubnemo/CompileDaemon
# https://github.com/olivere/go-container-debugging
RUN go get github.com/go-delve/delve/cmd/dlv

# ENTRYPOINT CompileDaemon -build="go build -o build/cart ./main.go" -command="./build/cart"
CMD ["dlv", "debug", "github.com/hoangnguyen1247/quickstart-lib-go", "--headless", "--listen=:2345", "--api-version=2", "--log"]
